### ISSUE TITLE
Why such check of keys?

### ISSUE THREAD

**Issue by s1lver** [yiisoft/cache-redis#6]
### What steps will reproduce the problem?

Migrate from Yii2

### What is the expected result?

Don't see the different in behavior

### What do you get instead?

I get an exception

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 1.0.0
| PHP version      |  8.0.21
| Operating system | Alpine

I have a method that automatically generates a key based on the name of the method and the passed parameters. And it worked well enough. There is an interesting check in the new version, the meaning of which I do not understand

```php
if (!is_string($key) || $key === '' || strpbrk($key, '{}()/\@:')) {
    throw new InvalidArgumentException('Invalid key value.');
}
```

Can you explain why such validation was introduced for the key?

This is basically ` '{}()/\@:'`

**Comment by samdark** [comment]
> Key - A string of at least one character that uniquely identifies a cached item. Implementing libraries MUST support keys consisting of the characters A-Z, a-z, 0-9, _, and . in any order in UTF-8 encoding and a length of up to 64 characters. Implementing libraries MAY support additional characters and encodings or longer lengths, but MUST support at least that minimum. Libraries are responsible for their own escaping of key strings as appropriate, but MUST be able to return the original unmodified key string. The following characters are reserved for future extensions and MUST NOT be supported by implementing libraries: {}()/\@:

That's from PSR-16: https://www.php-fig.org/psr/psr-16/#12-definitions
