### ISSUE TITLE
Cannot use 'FLUSHDB' with redis-cluster

### ISSUE THREAD

**Issue by s1lver** [yiisoft/cache-redis#7]
### What steps will reproduce the problem?
1) Set up Redis cluster
2) Call method `$this->instance->clear()`

```php
public function clear(): bool
{
    return $this->client->flushdb() !== null;
}
```

### What is the expected result?
Completed cleaning

### What do you get instead?
I get an exception

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 1.0.0
| PHP version      | 8.0.21
| Operating system | Alpine
| Redis                     | 6.2.6 - 7.0.4

**Comment by samdark** [comment]
What's the exception?

**Comment by s1lver** [comment]
> What's the exception?

Exception 'Predis\NotSupportedException' with message 'Cannot use 'FLUSHDB' with redis-cluster.'

**Comment by s1lver** [comment]
I wrote a couple of tests connecting to a Redis cluster. Can I change CI using single Docker config locally and in Github Actions?

How in general are local tests being launched now?

**Comment by samdark** [comment]
> Can I change CI using single Docker config locally and in Github Actions?

Isn't it possible to lauch cluster as a service in actions?

> How in general are local tests being launched now?

With a local instance of PHP/Redis.

**Comment by s1lver** [comment]
> > Can I change CI using single Docker config locally and in Github Actions?
> 
> Isn't it possible to lauch cluster as a service in actions?

Yes it is possible

**Comment by s1lver** [comment]
@samdark 
first to check I changed the CI and ran the current tests
https://github.com/yiisoft/cache-redis/runs/8004880416?check_suite_focus=true

Then I added identical tests with a connection to the cluster
https://github.com/yiisoft/cache-redis/runs/8005031578?check_suite_focus=true

**Comment by s1lver** [comment]
Maybe check the activity of the cluster like this? And if it is active, then execute another command to clear

```
172.20.128.3:6382> info Cluster
# Cluster
cluster_enabled:1
```

**Comment by s1lver** [comment]
Predis independently routes commands, when specifying Redis nodes in the cluster, to the appropriate nodes, depending on the keys that are specified in the commands.

Therefore, you can use the `set` and `get` methods to implement `MGET` and `MSET`.

Implementing something like this

```php
$slot = $client->getConnection()->executeCommand(new RawCommand('CLUSTER KEYSLOT', [$key]));
$client->getConnection()->executeCommand(new RawCommand('CLUSTER SETSLOT', [$slot, 'IMPORTING']));
$valuesFromCache[$key] = $client->getConnection()->executeCommand(new RawCommand('GET', [$key]));
$client->getConnection()->executeCommand(new RawCommand('CLUSTER SETSLOT', [$slot, 'NODE']));
```
 would be redundant.

You can also manually check the receipt of the key in the cluster using the `redis-cli`
![image](https://github.com/yiisoft/cache-redis/assets/4567634/2669e813-1038-4338-a60a-62e4cf365876)
